ALTER TYPE "LlmProvider" ADD VALUE IF NOT EXISTS 'DEEPSEEK';
ALTER TYPE "LlmProvider" ADD VALUE IF NOT EXISTS 'QWEN';

ALTER TABLE "app_settings"
ADD COLUMN IF NOT EXISTS "deepseek_api_key" TEXT,
ADD COLUMN IF NOT EXISTS "qwen_api_key" TEXT,
ADD COLUMN IF NOT EXISTS "llm_routing_json" JSONB;
